### PR TITLE
Update matrix.cpp

### PR DESCRIPTION
**Pull request by YomnaJehad**

### CODE REVIEW

**Comment by yibrahimmoos** [comment]
this function `static matrix operator * (matrix& m)` 
should be `matrix matrix::operator * (matrix& m)`,
then add the header to matrix.h file `matrix operator * (matrix& m)`  and we're good to go :+1:

**Review by yibrahimmoos — CHANGES_REQUESTED** [review]
add the header file

**Comment by YoussephAhmed** [comment]
need the prototype in the header file first , and then you don't need to have what you call static operator , let the multiply be ordinary function or static first and then call this function in the operator @YomnaJehad @YousifHmada

**Review by YoussephAhmed — COMMENTED** [review]
need the prototype in the header file first , and then you don't need to have what you call static operator , let the multiply be ordinary function or static first and then call this function in the operator @YomnaJehad @YousifHmada

**Pull request closed without merging**
